services:
  mysql:
    container_name: mysql-db
    image: mysql:5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop-net
    volumes:
      - mysql_data:/var/lib/mysql

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:1.7.8
    restart: always
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: prestashop
      PS_SHOP_NAME: "Włóczkowy Świat"
      PS_LANGUAGE: pl
      PS_COUNTRY: PL
      ADMIN_MAIL: admin@prestashop.com
      ADMIN_PASSWD: prestashop
      PS_FOLDER_ADMIN: admin123
      PS_FOLDER_INSTALL: install
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_DEV_MODE: 1
    ports:
      - 8080:80
    networks:
      - prestashop-net
    volumes:
      - prestashop:/var/www/html

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_ARBITRARY: 1
    networks:
      - prestashop-net

networks:
  prestashop-net:

volumes:
  mysql_data:
  prestashop: